- id: pr-status-check
  name: PR Status check
  description: test
  entry: bash -c 'chmod +x ./scripts/pr_status_checker.sh && ./scripts/pr_status_checker.sh'
  language: script
  always_run: true
  stages: [pre-merge-commit]
